name: Build RDS exporter docker image
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.15'

      - name: build binary
        run: |
          get -u github.com/prometheus/promu

          go version
          git submodule update --init --recursive
          cd rds_exporter/
          promu build 

          echo $(ls ./)
      