name: Build RDS exporter docker image
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.15'

      - name: build binary
        run: |
          go version
          go env
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

          mkdir -p /home/runner/go/src/lowid/rds_exporter
          git submodule update --init --recursive
          cd rds_exporter/

          cp -r . /home/runner/go/src/lowid/rds_exporter
          cd /home/runner/go/src/lowid/rds_exporter
          
          echo 'get deps'
          dep ensure
          echo 'Start build..'
          GO111MODULE=off go build

          echo $(ls ./)
      