name: Build RDS exporter docker image
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.15'

      - name: build binary
        run: |
          go version
          git submodule update --init --recursive
          cd rds_exporter/
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          echo 'get deps'
          dep ensure
          echo 'Start build..'
          go build

          echo $(ls ./)
      